// packages/core/react/use-completion.ts
import { useCallback, useEffect, useId, useRef, useState } from 'react';
import useSWR from 'swr';
import { readDataStream } from '../shared/read-data-stream';
import {
  JSONValue,
  RequestOptions,
  UseCompletionOptions,
} from '../shared/types';
import { COMPLEX_HEADER, createChunkDecoder } from '../shared/utils';

export type UseCompletionHelpers = {
  /** The current completion result */
  completion: string;
  /**
   * Send a new prompt to the API endpoint and update the completion state.
   */
  complete: (
    prompt: string,
    options?: RequestOptions,
  ) => Promise<string | null | undefined>;
  /** The error object of the API request */
  error: undefined | Error;
  /**
   * Abort the current API request but keep the generated tokens.
   */
  stop: () => void;
  /**
   * Update the `completion` state locally.
   */
  setCompletion: (completion: string) => void;
  /** The current value of the input */
  input: string;
  /** setState-powered method to update the input value */
  setInput: React.Dispatch<React.SetStateAction<string>>;
  /**
   * An input/textarea-ready onChange handler to control the value of the input
   * @example
   * ```jsx
   * <input onChange={handleInputChange} value={input} />
   * ```
   */
  handleInputChange: (
    e:
      | React.ChangeEvent<HTMLInputElement>
      | React.ChangeEvent<HTMLTextAreaElement>,
  ) => void;
  /**
   * Form submission handler to automatically reset input and append a user message
   * @example
   * ```jsx
   * <form onSubmit={handleSubmit}>
   *  <input onChange={handleInputChange} value={input} />
   * </form>
   * ```
   */
  handleSubmit: (e: React.FormEvent<HTMLFormElement>) => void;
  /** Whether the API request is in progress */
  isLoading: boolean;
  /** Additional data added on the server via StreamData */
  data?: JSONValue[] | undefined;
};

export function useCompletion({
  api = '/api/completion',
  id,
  initialCompletion = '',
  initialInput = '',
  credentials,
  headers,
  body,
  onResponse,
  onFinish,
  onError,
}: UseCompletionOptions = {}): UseCompletionHelpers {
  // Generate an unique id for the completion if not provided.
  const hookId = useId();
  const completionId = id || hookId;

  // Store the completion state in SWR, using the completionId as the key to share states.
  const { data, mutate } = useSWR<string>([api, completionId], null, {
    fallbackData: initialCompletion,
  });

  const { data: isLoading = false, mutate: mutateLoading } = useSWR<boolean>(
    [completionId, 'loading'],
    null,
  );

  const { data: streamData, mutate: mutateStreamData } = useSWR<
    JSONValue[] | undefined
  >([completionId, 'streamData'], null);

  const [error, setError] = useState<undefined | Error>(undefined);
  const completion = data!;

  // Abort controller to cancel the current API call.
  const [abortController, setAbortController] =
    useState<AbortController | null>(null);

  const extraMetadataRef = useRef({
    credentials,
    headers,
    body,
  });
  useEffect(() => {
    extraMetadataRef.current = {
      credentials,
      headers,
      body,
    };
  }, [credentials, headers, body]);

  const triggerRequest = useCallback(
    async (prompt: string, options?: RequestOptions) => {
      try {
        mutateLoading(true);
        setError(undefined);

        const abortController = new AbortController();
        setAbortController(abortController);

        // Empty the completion immediately.
        mutate('', false);

        const res = await fetch(api, {
          method: 'POST',
          body: JSON.stringify({
            prompt,
            ...extraMetadataRef.current.body,
            ...options?.body,
          }),
          credentials: extraMetadataRef.current.credentials,
          headers: {
            ...extraMetadataRef.current.headers,
            ...options?.headers,
          },
          signal: abortController.signal,
        }).catch(err => {
          throw err;
        });

        if (onResponse) {
          try {
            await onResponse(res);
          } catch (err) {
            throw err;
          }
        }

        if (!res.ok) {
          throw new Error(
            (await res.text()) || 'Failed to fetch the chat response.',
          );
        }

        if (!res.body) {
          throw new Error('The response body is empty.');
        }

        let result = '';
        const reader = res.body.getReader();

        const isComplexMode = res.headers.get(COMPLEX_HEADER) === 'true';

        if (isComplexMode) {
          for await (const { type, value } of readDataStream(reader, {
            isAborted: () => abortController === null,
          })) {
            switch (type) {
              case 'text': {
                result += value;
                mutate(result, false);
                break;
              }
              case 'data': {
                mutateStreamData(
                  [...(streamData || []), ...(value || [])],
                  false,
                );
                break;
              }
            }
          }
        } else {
          const decoder = createChunkDecoder();

          while (true) {
            const { done, value } = await reader.read();
            if (done) {
              break;
            }

            // Update the completion state with the new message tokens.
            result += decoder(value);
            mutate(result, false);

            // The request has been aborted, stop reading the stream.
            if (abortController === null) {
              reader.cancel();
              break;
            }
          }
        }

        if (onFinish) {
          onFinish(prompt, result);
        }

        setAbortController(null);
        return result;
      } catch (err) {
        // Ignore abort errors as they are expected.
        if ((err as any).name === 'AbortError') {
          setAbortController(null);
          return null;
        }

        if (err instanceof Error) {
          if (onError) {
            onError(err);
          }
        }

        setError(err as Error);
      } finally {
        mutateLoading(false);
      }
    },
    [
      mutate,
      mutateLoading,
      api,
      extraMetadataRef,
      setAbortController,
      onResponse,
      onFinish,
      onError,
      setError,
      streamData,
      mutateStreamData,
    ],
  );

  const stop = useCallback(() => {
    if (abortController) {
      abortController.abort();
      setAbortController(null);
    }
  }, [abortController]);

  const setCompletion = useCallback(
    (completion: string) => {
      mutate(completion, false);
    },
    [mutate],
  );

  const complete = useCallback<UseCompletionHelpers['complete']>(
    async (prompt, options) => {
      return triggerRequest(prompt, options);
    },
    [triggerRequest],
  );

  const [input, setInput] = useState(initialInput);

  const handleSubmit = useCallback(
    (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault();
      if (!input) return;
      return complete(input);
    },
    [input, complete],
  );

  const handleInputChange = (e: any) => {
    setInput(e.target.value);
  };

  return {
    completion,
    complete,
    error,
    setCompletion,
    stop,
    input,
    setInput,
    handleInputChange,
    handleSubmit,
    isLoading,
    data: streamData,
  };
}

// packages/core/solid/use-completion.ts
import { Accessor, Resource, Setter, createSignal } from 'solid-js';
import { useSWRStore } from 'solid-swr-store';
import { createSWRStore } from 'swr-store';
import type {
  JSONValue,
  RequestOptions,
  UseCompletionOptions,
} from '../shared/types';
import { COMPLEX_HEADER, createChunkDecoder } from '../shared/utils';
import { readDataStream } from '../shared/read-data-stream';

export type UseCompletionHelpers = {
  /** The current completion result */
  completion: Resource<string>;
  /** The error object of the API request */
  error: Accessor<undefined | Error>;
  /**
   * Send a new prompt to the API endpoint and update the completion state.
   */
  complete: (
    prompt: string,
    options?: RequestOptions,
  ) => Promise<string | null | undefined>;
  /**
   * Abort the current API request but keep the generated tokens.
   */
  stop: () => void;
  /**
   * Update the `completion` state locally.
   */
  setCompletion: (completion: string) => void;
  /** The current value of the input */
  input: Accessor<string>;
  /** Signal Setter to update the input value */
  setInput: Setter<string>;
  /**
   * Form submission handler to automatically reset input and append a user message
   * @example
   * ```jsx
   * <form onSubmit={handleSubmit}>
   *  <input value={input()} />
   * </form>
   * ```
   */
  handleSubmit: (e: any) => void;
  /** Whether the API request is in progress */
  isLoading: Accessor<boolean>;
  /** Additional data added on the server via StreamData */
  data: Accessor<JSONValue[] | undefined>;
};

let uniqueId = 0;

const store: Record<string, any> = {};
const completionApiStore = createSWRStore<any, string[]>({
  get: async (key: string) => {
    return store[key] ?? [];
  },
});

export function useCompletion({
  api = '/api/completion',
  id,
  initialCompletion = '',
  initialInput = '',
  credentials,
  headers,
  body,
  onResponse,
  onFinish,
  onError,
}: UseCompletionOptions = {}): UseCompletionHelpers {
  // Generate an unique id for the completion if not provided.
  const completionId = id || `completion-${uniqueId++}`;

  const key = `${api}|${completionId}`;
  const data = useSWRStore(completionApiStore, () => [key], {
    initialData: initialCompletion,
  });

  const mutate = (data: string) => {
    store[key] = data;
    return completionApiStore.mutate([key], {
      data,
      status: 'success',
    });
  };

  // Because of the `initialData` option, the `data` will never be `undefined`.
  const completion = data as Resource<string>;

  const [error, setError] = createSignal<undefined | Error>(undefined);
  const [streamData, setStreamData] = createSignal<JSONValue[] | undefined>(
    undefined,
  );
  const [isLoading, setIsLoading] = createSignal(false);

  let abortController: AbortController | null = null;
  async function triggerRequest(prompt: string, options?: RequestOptions) {
    try {
      setError(undefined);
      setIsLoading(true);

      abortController = new AbortController();

      // Empty the completion immediately.
      mutate('');

      const res = await fetch(api, {
        method: 'POST',
        body: JSON.stringify({
          prompt,
          ...body,
          ...options?.body,
        }),
        headers: {
          ...headers,
          ...options?.headers,
        },
        signal: abortController.signal,
        credentials,
      }).catch(err => {
        throw err;
      });

      if (onResponse) {
        try {
          await onResponse(res);
        } catch (err) {
          throw err;
        }
      }

      if (!res.ok) {
        throw new Error(
          (await res.text()) || 'Failed to fetch the chat response.',
        );
      }

      if (!res.body) {
        throw new Error('The response body is empty.');
      }

      let result = '';
      const reader = res.body.getReader();

      const isComplexMode = res.headers.get(COMPLEX_HEADER) === 'true';

      if (isComplexMode) {
        const existingData = streamData() ?? [];

        for await (const { type, value } of readDataStream(reader, {
          isAborted: () => abortController === null,
        })) {
          switch (type) {
            case 'text': {
              result += value;
              mutate(result);
              break;
            }
            case 'data': {
              setStreamData([...existingData, ...(value ?? [])]);
              break;
            }
          }
        }
      } else {
        const decoder = createChunkDecoder();

        while (true) {
          const { done, value } = await reader.read();
          if (done) {
            break;
          }
          // Update the chat state with the new message tokens.
          result += decoder(value);
          mutate(result);

          // The request has been aborted, stop reading the stream.
          if (abortController === null) {
            reader.cancel();
            break;
          }
        }
      }

      if (onFinish) {
        onFinish(prompt, result);
      }

      abortController = null;
      return result;
    } catch (err) {
      // Ignore abort errors as they are expected.
      if ((err as any).name === 'AbortError') {
        abortController = null;
        return null;
      }

      if (onError && error instanceof Error) {
        onError(error);
      }

      setError(err as Error);
    } finally {
      setIsLoading(false);
    }
  }

  const complete: UseCompletionHelpers['complete'] = async (
    prompt: string,
    options?: RequestOptions,
  ) => {
    return triggerRequest(prompt, options);
  };

  const stop = () => {
    if (abortController) {
      abortController.abort();
      abortController = null;
    }
  };

  const setCompletion = (completion: string) => {
    mutate(completion);
  };

  const [input, setInput] = createSignal(initialInput);

  const handleSubmit = (e: any) => {
    e.preventDefault();
    const inputValue = input();
    if (!inputValue) return;
    return complete(inputValue);
  };

  return {
    completion,
    complete,
    error,
    stop,
    setCompletion,
    input,
    setInput,
    handleSubmit,
    isLoading,
    data: streamData,
  };
}
