// examples/sveltekit-openai/src/routes/chat/+page.svelte
<script lang="ts">
  import ArrowUp from '$lib/components/icons/arrow-up.svelte';
  import Button from '$lib/components/ui/button/button.svelte';
  import { Textarea } from '$lib/components/ui/textarea/index.js';
  import { Chat } from '@ai-sdk/svelte';

  const chat = new Chat({
    maxSteps: 5,

    // run client-side tools that are automatically executed:
    async onToolCall({ toolCall }) {
      // artificial 2 second delay
      await new Promise(resolve => setTimeout(resolve, 2000));

      if (toolCall.toolName === 'getLocation') {
        const cities = ['New York', 'Los Angeles', 'Chicago', 'San Francisco'];
        return cities[Math.floor(Math.random() * cities.length)];
      }
    },
  });

  const disabled = $derived(chat.status !== 'ready');

  function mapRoleToClass(role: string) {
    return role === 'assistant'
      ? 'bg-primary text-secondary rounded-md'
      : 'bg-secondary text-primary rounded-md justify-self-end';
  }
</script>

<main class="flex flex-col items-center h-dvh w-dvw">
  <div
    class="grid h-full w-full max-w-4xl grid-cols-1 grid-rows-[1fr,120px] p-2"
  >
    <div class="w-full h-full overflow-y-auto">
      {#each chat.messages as message (message.id)}
        <div
          class="{mapRoleToClass(
            message.role,
          )} my-2 max-w-[80%] p-2 flex flex-col gap-2"
        >
          {#each message.parts as part, i (i)}
            {#if part.type === 'text'}
              {part.text}
            {:else if part.type === 'tool-invocation'}
              {@const toolCallId = part.toolInvocation.toolCallId}
              {@const toolName = part.toolInvocation.toolName}
              {@const state = part.toolInvocation.state}

              {#if toolName === 'askForConfirmation'}
                {#if state === 'call'}
                  <div class="flex flex-col gap-2">
                    {part.toolInvocation.args.message}
                    <div class="flex gap-2">
                      <Button
                        variant="default"
                        onclick={() =>
                          chat.addToolResult({
                            toolCallId,
                            result: 'Yes, confirmed',
                          })}>Yes</Button
                      >
                      <Button
                        variant="secondary"
                        onclick={() =>
                          chat.addToolResult({
                            toolCallId,
                            result: 'No, denied',
                          })}>No</Button
                      >
                    </div>
                  </div>
                {:else if state === 'result'}
                  <div class="text-gray-500">
                    {part.toolInvocation.result}
                  </div>
                {/if}
              {:else if toolName === 'getLocation'}
                {#if state === 'call'}
                  <div class="text-gray-500">Getting location...</div>
                {:else if state === 'result'}
                  <div class="text-gray-500">
                    Location: {part.toolInvocation.result}
                  </div>
                {/if}
              {:else if toolName === 'getWeatherInformation'}
                {#if state === 'partial-call'}
                  <pre>{JSON.stringify(part.toolInvocation, null, 2)}</pre>
                {:else if state === 'call'}
                  <div class="text-gray-500">
                    Getting weather information for {part.toolInvocation.args
                      .city}...
                  </div>
                {:else if state === 'result'}
                  <div class="text-gray-500">
                    Weather in {part.toolInvocation.args.city}: {part
                      .toolInvocation.result}
                  </div>
                {/if}
              {/if}
            {/if}
          {/each}
        </div>
      {/each}
    </div>
    <form class="relative" onsubmit={chat.handleSubmit}>
      <Textarea
        bind:value={chat.input}
        placeholder="Send a message..."
        class="h-full"
        onkeydown={event => {
          if (event.key === 'Enter' && !event.shiftKey) {
            event.preventDefault();
            chat.handleSubmit();
          }
        }}
      />
      <Button
        aria-label="Send message"
        {disabled}
        type="submit"
        size="icon"
        class="absolute bottom-3 right-3"
      >
        <ArrowUp />
      </Button>
    </form>
  </div>
</main>

// examples/next-openai/app/use-chat-persistence-single-message-tools/[id]/chat.tsx
'use client';

import { createIdGenerator } from 'ai';
import { Message, useChat } from '@ai-sdk/react';

export default function Chat({
  id,
  initialMessages,
}: { id?: string | undefined; initialMessages?: Message[] } = {}) {
  const { input, addToolResult, handleInputChange, handleSubmit, messages } =
    useChat({
      api: '/api/use-chat-persistence-single-message-tools',
      id, // use the provided chatId
      initialMessages, // initial messages if provided
      sendExtraMessageFields: true, // send id and createdAt for each message
      generateId: createIdGenerator({ prefix: 'msgc', size: 16 }), // id format for client-side messages

      // only send the last message to the server:
      experimental_prepareRequestBody({ messages, id }) {
        return { message: messages[messages.length - 1], id };
      },

      maxSteps: 5,
      // run client-side tools that are automatically executed:
      async onToolCall({ toolCall }) {
        if (toolCall.toolName === 'getLocation') {
          const cities = [
            'New York',
            'Los Angeles',
            'Chicago',
            'San Francisco',
          ];
          return cities[Math.floor(Math.random() * cities.length)];
        }
      },
    });

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      {messages?.map(message => (
        <div key={message.id} className="whitespace-pre-wrap">
          <strong>{`${message.role}: `}</strong>
          {message.parts.map((part, index) => {
            switch (part.type) {
              case 'text':
                return <div key={index}>{part.text}</div>;
              case 'step-start':
                return index > 0 ? (
                  <div key={index} className="text-gray-500">
                    <hr className="my-2 border-gray-300" />
                  </div>
                ) : null;
              case 'tool-invocation': {
                switch (part.toolInvocation.toolName) {
                  case 'askForConfirmation': {
                    switch (part.toolInvocation.state) {
                      case 'call':
                        return (
                          <div key={index} className="text-gray-500">
                            {part.toolInvocation.args.message}
                            <div className="flex gap-2">
                              <button
                                className="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700"
                                onClick={() =>
                                  addToolResult({
                                    toolCallId: part.toolInvocation.toolCallId,
                                    result: 'Yes, confirmed.',
                                  })
                                }
                              >
                                Yes
                              </button>
                              <button
                                className="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-700"
                                onClick={() =>
                                  addToolResult({
                                    toolCallId: part.toolInvocation.toolCallId,
                                    result: 'No, denied',
                                  })
                                }
                              >
                                No
                              </button>
                            </div>
                          </div>
                        );
                      case 'result':
                        return (
                          <div key={index} className="text-gray-500">
                            Location access allowed:{' '}
                            {part.toolInvocation.result}
                          </div>
                        );
                    }
                    break;
                  }

                  case 'getLocation': {
                    switch (part.toolInvocation.state) {
                      case 'call':
                        return (
                          <div key={index} className="text-gray-500">
                            Getting location...
                          </div>
                        );
                      case 'result':
                        return (
                          <div key={index} className="text-gray-500">
                            Location: {part.toolInvocation.result}
                          </div>
                        );
                    }
                    break;
                  }

                  case 'getWeatherInformation': {
                    switch (part.toolInvocation.state) {
                      // example of pre-rendering streaming tool calls:
                      case 'partial-call':
                        return (
                          <pre key={index}>
                            {JSON.stringify(part.toolInvocation, null, 2)}
                          </pre>
                        );
                      case 'call':
                        return (
                          <div key={index} className="text-gray-500">
                            Getting weather information for{' '}
                            {part.toolInvocation.args.city}...
                          </div>
                        );
                      case 'result':
                        return (
                          <div key={index} className="text-gray-500">
                            Weather in {part.toolInvocation.args.city}:{' '}
                            {part.toolInvocation.result}
                          </div>
                        );
                    }
                    break;
                  }
                }
              }
            }
          })}
          <br />
        </div>
      ))}

      <form onSubmit={handleSubmit}>
        <input
          className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
        />
      </form>
    </div>
  );
}
