// examples/sveltekit-openai/src/routes/use-chat-streamdata/+page.svelte
<script lang="ts">
  import { useChat } from '@ai-sdk/svelte';

  const { input, status, handleSubmit, messages, data, setData } = useChat({
    api: '/api/use-chat-streamdata',
  });
</script>

<section>
  <h1>useChat</h1>

  {#if $data}
    <pre class="p-4 text-sm bg-gray-100">
      {JSON.stringify($data, null, 2)}
    </pre>
    <button
      on:click={() => setData(undefined)}
      class="px-4 py-2 mt-2 text-white bg-blue-500 rounded hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"
    >
      Clear Data
    </button>
  {/if}

  <ul>
    {#each $messages as message}
      <li class="whitespace-pre-wrap">
        <strong>{message.role}: </strong>
        {message.content}
      </li>
    {/each}
  </ul>

  <form on:submit={handleSubmit}>
    <input
      bind:value={$input}
      disabled={$status !== 'ready'}
      class="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
      placeholder="Say something..."
    />
    <button type="submit">Send</button>
  </form>
</section>

<style>
  section {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    flex: 0.6;
  }

  h1 {
    width: 100%;
  }
</style>

// examples/next-openai/app/use-chat-streamdata/page.tsx
'use client';

import { Message, useChat } from '@ai-sdk/react';

export default function Chat() {
  const { messages, input, handleInputChange, handleSubmit, data, setData } =
    useChat({ api: '/api/use-chat-streamdata' });

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      {data && (
        <>
          <pre className="p-4 text-sm bg-gray-100">
            {JSON.stringify(data, null, 2)}
          </pre>
          <button
            onClick={() => setData(undefined)}
            className="px-4 py-2 mt-2 text-white bg-blue-500 rounded hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"
          >
            Clear Data
          </button>
        </>
      )}

      {messages?.map((m: Message) => (
        <div key={m.id} className="whitespace-pre-wrap">
          <strong>{`${m.role}: `}</strong>
          {m.content}
          {m.annotations && (
            <pre className="p-4 text-sm bg-gray-100">
              {JSON.stringify(m.annotations, null, 2)}
            </pre>
          )}
          <br />
          <br />
        </div>
      ))}

      <form
        onSubmit={e => {
          setData(undefined); // clear stream data
          handleSubmit(e);
        }}
      >
        <input
          className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
        />
      </form>
    </div>
  );
}
