// packages/svelte/src/routes/chat/+page.svelte
<script lang="ts">
  import ArrowUp from "$demo-lib/components/icons/arrow-up.svelte";
  import Button from "$demo-lib/components/ui/button/button.svelte";
  import { Textarea } from "$demo-lib/components/ui/textarea/index.js";
  import { Chat } from "$lib/index.js";

  const chat = new Chat();
  const disabled = $derived(chat.status !== "ready");

  function mapRoleToClass(role: string) {
    return role === "assistant"
      ? "bg-primary text-secondary rounded-md"
      : "bg-secondary text-primary rounded-md justify-self-end";
  }
</script>

<main class="flex h-dvh w-dvw flex-col items-center">
  <div
    class="grid h-full w-full max-w-4xl grid-cols-1 grid-rows-[1fr,120px] p-2"
  >
    <div class="h-full w-full overflow-y-auto">
      {#each chat.messages as message (message.id)}
        <div class="{mapRoleToClass(message.role)} my-2 max-w-[80%] p-2">
          {message.content}
        </div>
      {/each}
    </div>
    <form class="relative" onsubmit={chat.handleSubmit}>
      <Textarea
        bind:value={chat.input}
        placeholder="Send a message..."
        class="h-full"
        onkeydown={(event) => {
          if (event.key === "Enter" && !event.shiftKey) {
            event.preventDefault();
            chat.handleSubmit();
          }
        }}
      />
      <Button
        aria-label="Send message"
        {disabled}
        type="submit"
        size="icon"
        class="absolute bottom-3 right-3"
      >
        <ArrowUp />
      </Button>
    </form>
  </div>
</main>

// examples/next-cohere/app/use-chat-resilient-persistence/[id]/chat.tsx
'use client';

import { Message, useChat } from '@ai-sdk/react';
import { createIdGenerator } from 'ai';

export default function Chat({
  id,
  initialMessages,
}: { id?: string | undefined; initialMessages?: Message[] } = {}) {
  const { input, status, handleInputChange, handleSubmit, messages, stop } =
    useChat({
      api: '/api/use-chat-resilient-persistence',
      id, // use the provided chatId
      initialMessages, // initial messages if provided
      sendExtraMessageFields: true, // send id and createdAt for each message
      generateId: createIdGenerator({ prefix: 'msgc', size: 16 }), // id format for client-side messages
    });

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      {messages.map(m => (
        <div key={m.id} className="whitespace-pre-wrap">
          {m.role === 'user' ? 'User: ' : 'AI: '}
          {m.content}
        </div>
      ))}

      <form onSubmit={handleSubmit}>
        <input
          className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
          disabled={status !== 'ready'}
        />
        {status === 'streaming' && (
          <button
            className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
            type="submit"
            onClick={stop}
          >
            Stop
          </button>
        )}
      </form>
    </div>
  );
}
