// examples/next-openai/app/use-chat-throttle/page.tsx
'use client';

import { useChat, defaultChatStore } from '@ai-sdk/react';
import { useLayoutEffect, useRef } from 'react';

export default function Chat() {
  const renderCount = useRef(0);
  useLayoutEffect(() => {
    console.log(`component rendered #${++renderCount.current}`);
  });

  const { messages, input, status, handleInputChange, handleSubmit } = useChat({
    chatStore: defaultChatStore({
      api: '/api/use-chat-throttle',
    }),
    experimental_throttle: 50,
  });

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      <h4 className="pb-4 text-xl font-bold text-gray-900 md:text-xl">
        useChat throttle example
      </h4>
      {messages.map(m => (
        <div key={m.id} className="whitespace-pre-wrap">
          {m.role === 'user' ? 'User: ' : 'AI: '}
          {m.parts
            .map(part => (part.type === 'text' ? part.text : ''))
            .join('')}
        </div>
      ))}
      <form onSubmit={handleSubmit}>
        <input
          className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
          disabled={status !== 'ready'}
        />
      </form>
    </div>
  );
}

// examples/nuxt-openai/pages/use-chat-throttle/index.vue
<script setup lang="ts">
import { useChat } from '@ai-sdk/vue';
import { computed, ref } from 'vue';

const input = ref('');
const { error, messages, sendMessage, status, stop } = useChat({
  // Reduce Markdown and tool rendering work during high-frequency streams.
  // Stream processing and callbacks still run for every incoming chunk.
  throttle: 50,
});

const disabled = computed(() => status.value !== 'ready');

function handleSubmit(event: Event) {
  event.preventDefault();

  if (input.value.trim() === '') {
    return;
  }

  sendMessage({ text: input.value });
  input.value = '';
}
</script>

<template>
  <div class="flex flex-col w-full max-w-md py-24 mx-auto stretch">
    <div v-for="message in messages" :key="message.id">
      {{ message.role === 'user' ? 'User: ' : 'AI: ' }}
      {{
        message.parts
          .map(part => (part.type === 'text' ? part.text : ''))
          .join('')
      }}
    </div>

    <div v-if="status === 'submitted' || status === 'streaming'" class="mt-4">
      <button type="button" @click="stop">Stop</button>
    </div>

    <div v-if="error" class="mt-4 text-red-500">
      {{ error.message }}
    </div>

    <form @submit="handleSubmit">
      <input
        v-model="input"
        class="fixed bottom-0 w-full max-w-md p-2 mb-8 border rounded"
        placeholder="Say something..."
        :disabled="disabled"
      />
    </form>
  </div>
</template>
