// packages/angular/src/lib/chat.ng.ts
import { signal } from '@angular/core';
import {
  AbstractChat,
  type ChatState,
  type ChatStatus,
  type UIMessage,
  type ChatInit,
} from 'ai';
export class Chat<
  UI_MESSAGE extends UIMessage = UIMessage,
> extends AbstractChat<UI_MESSAGE> {
  constructor(init: ChatInit<UI_MESSAGE>) {
    super({
      ...init,
      state: new AngularChatState(init.messages),
    });
  }
}

class AngularChatState<
  UI_MESSAGE extends UIMessage = UIMessage,
> implements ChatState<UI_MESSAGE> {
  readonly #messages = signal<UI_MESSAGE[]>([]);
  readonly #status = signal<ChatStatus>('ready');
  readonly #error = signal<Error | undefined>(undefined);

  get messages(): UI_MESSAGE[] {
    return this.#messages();
  }

  set messages(messages: UI_MESSAGE[]) {
    this.#messages.set([...messages]);
  }

  get status(): ChatStatus {
    return this.#status();
  }

  set status(status: ChatStatus) {
    this.#status.set(status);
  }

  get error(): Error | undefined {
    return this.#error();
  }

  set error(error: Error | undefined) {
    this.#error.set(error);
  }

  constructor(initialMessages: UI_MESSAGE[] = []) {
    this.#messages.set([...initialMessages]);
  }

  setMessages = (messages: UI_MESSAGE[]) => {
    this.#messages.set([...messages]);
  };

  pushMessage = (message: UI_MESSAGE) => {
    this.#messages.update(msgs => [...msgs, message]);
  };

  popMessage = () => {
    this.#messages.update(msgs => msgs.slice(0, -1));
  };

  replaceMessage = (index: number, message: UI_MESSAGE) => {
    this.#messages.update(msgs => {
      const copy = [...msgs];
      copy[index] = structuredClone(message);
      return copy;
    });
  };

  snapshot = <T>(thing: T): T => thing;
}

// packages/solid/src/chat.solid.ts
import { AbstractChat, ChatInit, ChatState, ChatStatus, UIMessage } from "ai";
import { Accessor, createSignal, Signal } from "solid-js";
import { createStore, produce, reconcile, SetStoreFunction } from "solid-js/store";




export class SolidChatState<UI_MESSAGE extends UIMessage> implements ChatState<UI_MESSAGE> {
  private messagesSignal: Signal<UI_MESSAGE[]>;
  private statusSignal: Signal<ChatStatus>;
  private errorSignal: Signal<Error | undefined>;

  constructor(initialMessages: UI_MESSAGE[] = []) {
    this.messagesSignal = createSignal(initialMessages);
    this.statusSignal = createSignal<ChatStatus>('ready');
    this.errorSignal = createSignal<Error | undefined>(undefined);
  }

  get status(): ChatStatus {
    return this.statusSignal[0]();
  }

  set status(status: ChatStatus) {
    const [, setStatus] = this.statusSignal;
    setStatus(status);
  }

  get messages(): UI_MESSAGE[] {
    const [messages] = this.messagesSignal;
    return messages();
  }

  set messages(messages: UI_MESSAGE[]) {
    const [, setMessages] = this.messagesSignal;
    setMessages([...messages]);
  }

  get error(): Error | undefined {
    return this.errorSignal[0]();
  }

  set error(error: Error | undefined) {
    this.errorSignal[1](() => error);
  }

  get statusAccessor(): Accessor<ChatStatus> {
    return this.statusSignal[0];
  }

  get errorAccessor(): Accessor<Error | undefined> {
    return this.errorSignal[0];
  }

  get messagesAccessor(): Accessor<UI_MESSAGE[]> {
    return this.messagesSignal[0];
  }

  pushMessage = (message: UI_MESSAGE) => {
    const [, setMessages] = this.messagesSignal;
    setMessages((m) => [...m.map(m => ({...m, parts: [...m.parts]})), message]);
  }
  popMessage = () => {
    const [, setMessages] = this.messagesSignal;
    setMessages((m) => [...m.map(m => ({...m, parts: [...m.parts]}))].slice(0, -1));
  }
  replaceMessage = (index: number, message: UI_MESSAGE) => {
    const [, setMessages] = this.messagesSignal;
    setMessages((m) => [...m.map(m => ({...m, parts: [...m.parts]}))].map((m, i) => i === index ? message : m));
  }
  snapshot = <T>(thing: T): T => structuredClone(thing);
}

export class Chat<
  UI_MESSAGE extends UIMessage,
> extends AbstractChat<UI_MESSAGE> {
  #state: SolidChatState<UI_MESSAGE>;
  constructor({ messages, ...init }: ChatInit<UI_MESSAGE>) {
    const state = new SolidChatState<UI_MESSAGE>(messages);
    super({ ...init, state });
    this.#state = state;
  }

  get statusAccessor(): Accessor<ChatStatus> {
    return this.#state.statusAccessor;
  }

  get messages(): UI_MESSAGE[] {
    return this.#state.messages;
  }

  set messages(messages: UI_MESSAGE[]) {
    this.#state.messages = messages;
  }

  get errorAccessor(): Accessor<Error | undefined> {
    return this.#state.errorAccessor;
  }

  get messagesAccessor(): Accessor<UI_MESSAGE[]> {
    return this.#state.messagesAccessor;
  }
  
}
