// packages/react/src/setup-test-component.tsx
import { cleanup, render } from '@testing-library/react';
import { SWRConfig } from 'swr';

export const setupTestComponent = (
  TestComponent: React.ComponentType<any>,
  {
    init,
  }: {
    init?: (TestComponent: React.ComponentType<any>) => React.ReactNode;
  } = {},
) => {
  beforeEach(() => {
    // reset SWR cache to isolate tests:
    render(
      <SWRConfig value={{ provider: () => new Map() }}>
        {init?.(TestComponent) ?? <TestComponent />}
      </SWRConfig>,
    );
  });

  afterEach(() => {
    vi.restoreAllMocks();
    cleanup();
  });
};

// packages/solid/src/setup-test-component.tsx
import { cleanup, render } from '@solidjs/testing-library';
import { Store, SwrProvider } from 'solid-swr';
import { JSX, Component } from 'solid-js';

export const setupTestComponent = (
  TestComponent: Component<any>,
  {
    init,
  }: {
    init?: (TestComponent: Component<any>) => JSX.Element;
  } = {},
) => {
  beforeEach(() => {
    // reset SWR cache to isolate tests:
    render(() => (
      <SwrProvider value={{ store: new Store() }}>
        {init?.(TestComponent) ?? <TestComponent />}
      </SwrProvider>
    ));
  });

  afterEach(() => {
    vi.restoreAllMocks();
    cleanup();
  });
};
