// examples/next-openai/app/assistant/page.tsx
'use client';

import { Message, useAssistant as useAssistant } from 'ai/react';
import { useEffect, useRef } from 'react';

const roleToColorMap: Record<Message['role'], string> = {
  system: 'red',
  user: 'black',
  function: 'blue',
  tool: 'purple',
  assistant: 'green',
  data: 'orange',
};

export default function Chat() {
  const {
    status,
    messages,
    input,
    submitMessage,
    handleInputChange,
    error,
    stop,
  } = useAssistant({ api: '/api/assistant' });

  // When status changes to accepting messages, focus the input:
  const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    if (status === 'awaiting_message') {
      inputRef.current?.focus();
    }
  }, [status]);

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      {error != null && (
        <div className="relative px-6 py-4 text-white bg-red-500 rounded-md">
          <span className="block sm:inline">
            Error: {(error as any).toString()}
          </span>
        </div>
      )}

      {messages.map((m: Message) => (
        <div
          key={m.id}
          className="whitespace-pre-wrap"
          style={{ color: roleToColorMap[m.role] }}
        >
          <strong>{`${m.role}: `}</strong>
          {m.role !== 'data' && m.content}
          {m.role === 'data' && (
            <>
              {(m.data as any).description}
              <br />
              <pre className={'bg-gray-200'}>
                {JSON.stringify(m.data, null, 2)}
              </pre>
            </>
          )}
          <br />
          <br />
        </div>
      ))}

      {status === 'in_progress' && (
        <div className="w-full h-8 max-w-md p-2 mb-8 bg-gray-300 rounded-lg dark:bg-gray-600 animate-pulse" />
      )}

      <form onSubmit={submitMessage}>
        <input
          ref={inputRef}
          disabled={status !== 'awaiting_message'}
          className="fixed w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl bottom-14 ax-w-md bottom-4 "
          value={input}
          placeholder="What is the temperature in the living room?"
          onChange={handleInputChange}
        />
      </form>

      <button
        className="fixed bottom-0 w-full max-w-md p-2 mb-8 text-white bg-red-500 rounded-lg"
        onClick={stop}
      >
        Stop
      </button>
    </div>
  );
}

// examples/nuxt-openai/pages/assistant/index.vue
<script lang="ts" setup>
import { useAssistant } from '@ai-sdk/vue';
import type { Message } from '@ai-sdk/vue';

const roleToColorMap: Record<Message['role'], string> = {
  system: 'red',
  user: 'black',
  function: 'blue',
  tool: 'purple',
  assistant: 'green',
  data: 'orange',
};

const { messages, status, input, handleSubmit, error, stop } = useAssistant({
  api: '/api/assistant',
});

// Create a reference of the input element and focus on it when the component is mounted & the assistant status is 'awaiting_message'
const inputRef = ref<HTMLInputElement | null>(null);

watchEffect(() => {
  if (inputRef.value && status.value === 'awaiting_message') {
    inputRef.value.focus();
  }
});
</script>

<template>
  <div class="flex flex-col w-full max-w-md py-24 mx-auto stretch">
    <!-- Render Assistant API errors if any -->
    <div
      class="relative px-6 py-4 text-white bg-red-500 rounded-md"
      v-if="error"
    >
      <span class="block sm:inline"> Error: {{ error?.toString() }} </span>
    </div>

    <!-- Render Assistant Messages -->
    <div
      class="whitespace-pre-wrap"
      v-for="(message, index) in messages"
      :key="index"
      :style="{ color: roleToColorMap[message.role] }"
    >
      <strong>{{ `${message.role}: ` }}</strong>
      {{ message.role !== 'data' && message.content }}
      <template v-if="message.role === 'data'">
        {{ (message.data as any)?.description }}
        <br />
        <pre class="bg-gray-200">{{
          JSON.stringify(message.data, null, 2)
        }}</pre>
      </template>
      <br />
      <br />
    </div>

    <!-- Render Assistant Status Indicator (In Progress) -->
    <div
      class="w-full h-8 max-w-md p-2 mb-8 bg-gray-300 rounded-lg dark:bg-gray-600 animate-pulse"
      v-if="status === 'in_progress'"
    ></div>

    <!-- Render Assistant Message Input Form -->
    <form @submit.prevent="(e) => handleSubmit(e as any)">
      <input
        ref="inputRef"
        :disabled="status === 'in_progress'"
        class="fixed w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl bottom-14 ax-w-md"
        v-model="input"
        placeholder="What is the temperature in the living room?"
      />
    </form>

    <button
      @click="stop"
      :disabled="status === 'awaiting_message'"
      class="fixed bottom-0 w-full max-w-md p-2 mb-8 text-white bg-red-500 rounded-lg disabled:opacity-50"
    >
      Stop
    </button>
  </div>
</template>
